spring:
  threads:
    virtual:
      enabled: true
  data:
    redis:
      cluster:
        nodes: 
          - 127.0.0.1:7000
          - 127.0.0.1:7001
          - 127.0.0.1:7002
      lettuce:
        pool:
          max-active: 200
          max-idle: 100
          min-idle: 25
      timeout: 50ms

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles:
        ratelimit.redis.latency: 0.95, 0.99
